### ISSUE TITLE
Default web page directory incorrect

### ISSUE THREAD

**Issue by white111** [oddwires/oddwires-alarm-system#2]
Install: Jessie lite
Hardware: Raspberry Pi B
Issue:
Had to change 
/etc/apache2/sites-enabled/default-ssl.conf

Was: DocumentRoot /var/www/html
Changed to:  DocumentRoot /var/www

Error Seen(from windows browser):
This error (HTTP 404 Not Found) means that Internet Explorer was able to connect to the website, but the page you wanted was not found. It’s possible that the webpage is temporarily unavailable. Alternatively, the website might have changed or removed the webpage.
For more information about HTTP errors, see Help.__

**Comment by oddwires** [comment]
Thanks for pointing this out. I havent looked at the code for a while, and it was orriginally written to work on Debian Wheezy - but looks like Debian Jessie is now the only option.

I'll dust of my develpoment rig and get the code updated.

**Comment by oddwires** [comment]
... although thinking about it....
The README.MD does state that this code is depricated.

So I'll check my [current repository](https://github.com/oddwires/alarm-system) against the Jessie image, and ensure that one is working.
